### ISSUE TITLE
calculate total KOI and view counts issue

### ISSUE THREAD

**Issue by inovatedTeam** [koii-network/tools#38]
missing createdAt params in the getTopContentPredicted api.
![image](https://user-images.githubusercontent.com/14047891/120136465-326f1180-c1a0-11eb-86f2-b5214928591b.png)

**Comment by AndreVallestero** [comment]
@inovatedTeam Does this issue still exist?

**Comment by AndreVallestero** [comment]
Closing as we're unable to reproduce
